// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7HKie_G914m6mGB_z9GGSxRMIlwwQhas',
    appId: '1:329507433240:web:176296720a496e95cf4c6d',
    messagingSenderId: '329507433240',
    projectId: 'rentalcar-e3d6b',
    authDomain: 'rentalcar-e3d6b.firebaseapp.com',
    storageBucket: 'rentalcar-e3d6b.appspot.com',
    measurementId: 'G-BF70H1ZSMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASmHSVQxqvbPga0e5-EinIX6tCWoepeSo',
    appId: '1:329507433240:android:52e42852e67b5233cf4c6d',
    messagingSenderId: '329507433240',
    projectId: 'rentalcar-e3d6b',
    storageBucket: 'rentalcar-e3d6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqBLuDxvqZJtxxtT2oJUJCNBGlE2dpzw0',
    appId: '1:329507433240:ios:36a15d9ed521d77dcf4c6d',
    messagingSenderId: '329507433240',
    projectId: 'rentalcar-e3d6b',
    storageBucket: 'rentalcar-e3d6b.appspot.com',
    iosBundleId: 'com.example.rentalCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqBLuDxvqZJtxxtT2oJUJCNBGlE2dpzw0',
    appId: '1:329507433240:ios:36a15d9ed521d77dcf4c6d',
    messagingSenderId: '329507433240',
    projectId: 'rentalcar-e3d6b',
    storageBucket: 'rentalcar-e3d6b.appspot.com',
    iosBundleId: 'com.example.rentalCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7HKie_G914m6mGB_z9GGSxRMIlwwQhas',
    appId: '1:329507433240:web:dc180e7ea0358023cf4c6d',
    messagingSenderId: '329507433240',
    projectId: 'rentalcar-e3d6b',
    authDomain: 'rentalcar-e3d6b.firebaseapp.com',
    storageBucket: 'rentalcar-e3d6b.appspot.com',
    measurementId: 'G-SE00C2PJ0J',
  );
}
